### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by diasdavid** [mntnr/name-your-contributors#16]
Hi @RichardLitt! I'm looking forward to start using this module more, there are just a couple of things I would love to have in order to do so which. I would like to know if they sounds like they fit in the scope of this module or if I just should go ahead and create one that fits my needs. :)  Features I'm looking for are:

- Exposing internal functions for individual use - Improved testing and usage cases
- Expose a `-o` `--output-path` option to be able to specify where the data gets written
- Use a streaming interface to avoid running out of memory https://github.com/RichardLitt/name-your-contributors/issues/15
- Expose a --flat option, where:
  - if true, the output becomes ndjson with the format
```sh
//example
"{ timeframe: <2017-10-12--2017-12-20>, project: <org/repo>, user: <username>, issuesCreated: <>,  commits: <>.. plus other data } \n"
```
  - if false, the output becomes just a coalesced json struct
```json
// example:
{
  "2017-10-12--2017-12-20": {
    "org/repo": {
      user1: {
        // all the interesting stats
      }
      user2: {
        // ...
      }
   }
  }
}
```
- support for a config file that lists several repos and timeframes, so that it generates it all in one swipe
- able to export to csv data
- Also, can the hours be dropped from since and until? Or at least, optional

Overall I just also need it to be working, which I'm being unsuccessful at the moment.

**Comment by RichardLitt** [comment]
Hey @diasdavid!

> Exposing internal functions for individual use - Improved testing and usage cases

Done!

> Expose a -o --output-path option to be able to specify where the data gets written

You should be able to pipe it. It now just spits out a single JSON. 

#15 shouldn't be an issue anymore. 

`--flat` sounds cool. Want to help with that? Same for config, csv, and hours. If not, we can just open issues for those and I'll get to them eventually.

**Comment by RichardLitt** [comment]
I've opened issues for each of your requests that are still relevant. Anything else? If not, let's close this and focus on those issues. 🎉

**Comment by RichardLitt** [comment]
Closing due to lack of response.
