### ISSUE TITLE
Automatically spit all contributors into an AUTHORS.md or CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by RichardLitt** [mntnr/name-your-contributors#46]
This should be possible, with the name of the user and a link. Perhaps a shim tool would be best, on top of this?

**Comment by tgetgood** [comment]
So you mean convert the json into a markdown list? Simple enough. I think something downstream from this tool might make the most sense. Do you have templates for the md files?

**Comment by RichardLitt** [comment]
Yes. I have two templates:

```
- [@username](https://github.com/username]
```

and 

```
USERNAME
USERNAME2
```

Pretty simple, really. Let's make a companion module, maybe?

**Comment by tgetgood** [comment]
Agreed. A simple downstream script like whodunnit is probably best.

**Comment by RichardLitt** [comment]
Another great one would add the contributors to the package.json in the contributors field.

**Comment by tgetgood** [comment]
I've added a `--md` option to [whodidwhat](https://github.com/mntnr/whodidwhat) which outputs the contributor list (sorted by gross number of contributions) in the first markdown format above.

Does that suffice for this need?

**Comment by RichardLitt** [comment]
Not quite. I need two other formats:

```
User Name <email>
```

This should match `git authors`.

And, I need something that works for npm for the package.json: https://docs.npmjs.com/files/package.json#people-fields-author-contributors

So:

```
{ "name" : "Barney Rubble"
, "email" : "b@rubble.com"
, "url" : "http://barnyrubble.tumblr.com/"
}
```

Or `"Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"`.

**Comment by Berkmann18** [comment]
Was there any progress on this?

**Comment by RichardLitt** [comment]
Doesn't look like it. :)

**Comment by Berkmann18** [comment]
Hum, okay, would it be better as a separate package or do you think it should be integrated into NYC?

**Comment by RichardLitt** [comment]
I think this was the original conception behind https://github.com/mntnr/whodidwhat. Haven't checked in a bit. That may close this issue.

**Comment by Berkmann18** [comment]
That makes sense.

**Comment by RichardLitt** [comment]
I'm still not convinced that whodidwhat needs to be a different module, though. But it does resolve this.

**Comment by Berkmann18** [comment]
Good to know, I was initially wondering if, given the use cases, another package or an extension to `whodidwhat` or NYC needed to be made.
