### ISSUE TITLE
Trace Contributions

### ISSUE THREAD

**Issue by tgetgood** [mntnr/name-your-contributors#51]
We already query exactly who does what and where. Which PR of which repo did so and so comment on? 

The current aggregation logic throws that away and just returns bucketed counts.

We need the option to keep the entire query response tree (cleaned up a bit, but no info thrown away).

**Comment by RichardLitt** [comment]
This will be useful for being able to autogenerate name-your-contributor-esque newsletters. Who did what, and why, and where.

**Comment by Berkmann18** [comment]
Ddi #61 fully addressed that or is there anything left to do?

**Comment by RichardLitt** [comment]
Looks good enough, to me!
