### ISSUE TITLE
Finer grained control of data gathered

### ISSUE THREAD

**Issue by tgetgood** [mntnr/name-your-contributors#52]
Grabbing everything like we currently do can get insanely expensive. Ways to get around this:

- Query tuning: look more carefully at the branching factors in the queries and reduce the cost of the average query

- Make reactions optional (and opt in). Reactions, as leaves in the tree, are the most expensive thing to query and not always of interest to end users. So this is a no brainer.

- Don't get commit authors from the API by default. This isn't an expensive query, but we have to throttle the pagination since github returns these requests fast enough for us to appear spammy when we don't wait between. There are two ways to go here: 1) allow the user to specify the path to a local clone of the repo which we can query directly, and 2) have a flag to get them from the API. To reiterate, grabbing from the API isn't untenable, plotly.js has ~14000 commits, so it takes 140 requests and 140 quota to get it all. That's not necessarily too much quota, but at a reasonable rate limit for requests the user could be waiting a while. So opt in. This relates to #47.

**Comment by RichardLitt** [comment]
Let's implement optional reactions, and opt-in commit authors with an option to get this from a local repo. Then let's work on the rest. \o/

**Comment by Berkmann18** [comment]
All three items seems to be resolved, is there anything left?
