### ISSUE TITLE
Add a Cache

### ISSUE THREAD

**Issue by tgetgood** [mntnr/name-your-contributors#60]
To daemonise effectively (regarding #48) we need a local cache on disk. Nothing fancy just hashes of the queries and timestamps. Global ttl.

This will also have a beneficial impact on development, and in normal use it will mean that if a query fails because it's too expensive (not in daemon mode) then the data grabbed does not get thrown away when you try again later.

**Comment by RichardLitt** [comment]
Sounds good to me.
