### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by RichardLitt** [mntnr/name-your-contributors#68]
Semantic release has broken. :( I don't know why, and it's annoying because the current version doesn't work.

**Comment by RichardLitt** [comment]
@gr2m any idea how to fix after semantic release breaks?

**Comment by gr2m** [comment]
Looks like a problem with the token:
https://travis-ci.org/mntnr/name-your-contributors/jobs/334670124#L1971

Did you change anything?

You can run `semantic-release-cli setup` again and then select the option to just log the tokens, then copy&paste them into travis, that should fix it. I can also help upgrade semantic-release to the latest version which has more helpful logging, but lets try the token first

**Comment by RichardLitt** [comment]
Not sure what changed. Updated all of the vars, and the build works now. I may have just needed to update the token. 

But it hasn't published the new version. Any ideas?

**Comment by gr2m** [comment]
the logs say npm & github tokens are invalid:
https://travis-ci.org/mntnr/name-your-contributors/jobs/338695571#L2153

Can you set `DEBUG=semantic-release` on travis and restart https://travis-ci.org/mntnr/name-your-contributors/jobs/338712595#L2260?

**Comment by RichardLitt** [comment]
Ok, I'm clearly not finding the right tokens. I copied them from my keychain after `semantic-release-cli setup` saved them there. And I encrypted them to work on Travis. What am I missing?

**Comment by gr2m** [comment]
what do you mean with "you escaped them to work on travis"? 

If you like, you can add me as admin to this repository and and the npm package and then I try to set it up from my side? Will make it easier for me to debug

**Comment by RichardLitt** [comment]
I mean that one of the keys wasn't working without escaping some of the characters in it.

**Comment by RichardLitt** [comment]
Done!

**Comment by gr2m** [comment]
I don’t think I have admin access to the repo yet

**Comment by gr2m** [comment]
ah got it now sorry

**Comment by RichardLitt** [comment]
This is fixed. Thanks @gr2m!
