### ISSUE TITLE
Get emails for users

### ISSUE THREAD

**Issue by RichardLitt** [mntnr/name-your-contributors#73]
It looks more and more like this is a must have. It means another query to get the user object. 

Necessary for #46.

**Comment by Berkmann18** [comment]
Does it really need to be in another query?
If not, does having the emails in the same one as say, the repo one, good?

**Comment by RichardLitt** [comment]
It's been a while since I looked over the code; it's possible that we don't need another query for this. Having emails in the same query works for me.

**Comment by Berkmann18** [comment]
Ah okay, in that case, my PR might do the trick :).

**Comment by RichardLitt** [comment]
\0/ Thanks, @Berkmann18. Keep pinging me for review on stuff! Just figured you being a maintainer might expedite things, especially as you're so keen and I've got limited time. :)

**Comment by Berkmann18** [comment]
Sure 😃, I'll see how nyc could give the labels for issues and PRs although I'm not too familiar with how GraphQL interacts with the Github API.

**Comment by RichardLitt** [comment]
Me neither! :D
