### ISSUE TITLE
commitComments and commitcomments in --full json

### ISSUE THREAD

**Issue by simonv3** [mntnr/name-your-contributors#98]
After running the command line query without --full and then running it with full I notice two commit comments entries, one with camel case and one without: `commitcomments` and `commitComments`. 

I haven't dug into reproducing it, but it seems to me like there should only be one of those.

**Comment by Berkmann18** [comment]
Thanks for pointing that out that when `--full` is used `commitCommentators` is changed to `commitcomments`. I've found the typo and will push a fix soon.

**Comment by simonv3** [comment]
Thanks for the super quick fix!

**Comment by Berkmann18** [comment]
@simonv3 You're welcome :).

**Comment by RichardLitt** [comment]
Thank you, both of you!

**Comment by Berkmann18** [comment]
@richardLitt You're welcome :)
